### ISSUE TITLE
Gruppenarbeit: Kernel

### ISSUE THREAD

**Issue by tme5092** [Lucasvo1/FHVOS#11]
Wie schaut unser Kernel aus?
Wie stellen wir uns das vor
Mi. 04.03.

**Comment by Lucasvo1** [comment]
Wie wir vereinbart haben am Freitag : ein monolitisches kernel? 

Mögliche Vorteilen:
* Schneller : weniger IPC daher weniger overhead beim kommunizieren
* Weniger code daher vielleicht auch weniger Bugs

Ein beispiel von eine mögliche Architektur: 
![image](https://cloud.githubusercontent.com/assets/2812611/6440890/237b9498-c0e2-11e4-8b5f-c5653a2c45a8.png)
